name: WormholeXTremeWorldsSpawn
main: de.luricos.bukkit.WormholeXTreme.WorldsSpawn
version: 0.1
author: alron
depend: [WormholeXTremeWorlds]
description: >
             Wormhole X-Treme Worlds Spawn! '/spawn' command for Wormhole X-Treme Worlds!
             
commands:
  spawn:
    description: Teleport to Wormhole World spawn.
    usage: |
           /<command>